### PR TITLE
Create a feature branch to initialize the project

### PR DESCRIPTION
**Pull request by joseph07-drack**
This is my first in-program project where I made in practice the tools and best practices I learnt during the program time.
Throughout this project I worked on different topics as listed below :

-**Markup**(HTML) where I create a **heading element**✅
-**Styling**(CSS) and where I create an **external styling file and where I apply a color to the HTML heading1**✅
-**GitHubActions** for online linters checkups✅
-**GitHubFlow** for good collaboration approach✅
-**Linters** for standard coding and catching error in the source code✅

### CODE REVIEW

**Review by julie-ify — CHANGES_REQUESTED** [review]
## Hi @joseph07-drack, 

Good job so far!

## Highlight!
- Good feature branch name ✔️ 
- Good commit messages ✔️ 


Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the review comments below ._

- [ ] Good job implementing most of the project requirements and setting up the linters 👍.  However, you do not have the Github action `.github/workflows.linters.yml` directory which makes sure that your linter checks are available on Github. Kindly follow this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to learn how to set up Github action with linters 😄 

- [x] Consider making your Pull Request description more descriptive by including a descriptive title telling you what changes are inside. and also a short summary describing introduced changes in more details. See good pull request description example [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

- [ ] The `test.md` file is currently being pushed to Github but it is to be ignored by git as per your project requirement. Please consider making sure that the `test.md` file is actually ignored by git.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by joseph07-drack** [comment]
Hey julie, happy to have as code reviewer.

I would to tell you that the test.md is currently located in the .gitignrore file. So i do not know how it keeps showing up in GitHub

**Comment by joseph07-drack** [comment]
Capture

**Comment by julie-ify** [comment]
Hi @joseph07-drack,

I think the issue is that you committed `test.md` file before you added it to `.gitignore` file. If this is the case, then delete the `test.md` file and make a commit. After making a commit, create `test.md` file again and make sure it is in `.gitignore` file. Finally, make a commit and push then check if it was successfully ignored.  I hope this helps 😄

**Comment by joseph07-drack** [comment]
Thanks julie-If.

I thing that I have to make a **push request** once I have finished to apply all changes.

**Comment by joseph07-drack** [comment]
Thanks julie-Ify

**Review by micheaol — CHANGES_REQUESTED** [review]
Hi @joseph07-drack, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- _Kindly give your pull request a more descriptive title and a short summary describing introduced changes in more detail as requested by the previous reviewer. Please check this [LINK](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) for help_

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by elmar8287 — APPROVED** [review]
Hi @joseph07-drack  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉🎉🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by joseph07-drack** [comment]
Thanks @elmar8287.

**Pull request merged**
